[package]
name = "elax-indexer"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = "1"
elax-store = { path = "../elax-store" }
