version: '3.8'

services:
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3

  minio-init:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      mc alias set bootstrap http://minio:9000 ${MINIO_ROOT_USER:-minioadmin} ${MINIO_ROOT_PASSWORD:-minioadmin};
      mc mb bootstrap/${ELACSYM_S3_BUCKET:-elacsym-data} || true;
      mc anonymous set download bootstrap/${ELACSYM_S3_BUCKET:-elacsym-data};
      exit 0;
      "

  indexer-1:
    image: ${ELACSYM_IMAGE:-elacsym:latest}
    environment:
      ELACSYM_NODE_ID: indexer-1
      ELACSYM_NODE_ROLE: indexer
      AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER:-minioadmin}
      AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD:-minioadmin}
      ELACSYM_STORAGE_S3_BUCKET: ${ELACSYM_S3_BUCKET:-elacsym-data}
      ELACSYM_STORAGE_S3_REGION: ${ELACSYM_S3_REGION:-us-east-1}
      ELACSYM_STORAGE_S3_ENDPOINT: ${ELACSYM_S3_ENDPOINT:-http://minio:9000}
      ELACSYM_STORAGE_S3_WAL_PREFIX: ${ELACSYM_WAL_PREFIX:-production}
    volumes:
      - ./config-indexer.toml:/etc/elacsym/config.toml
      - indexer1_cache:/var/cache/elacsym
    ports:
      - "3001:3000"
    depends_on:
      - minio-init

  indexer-2:
    image: ${ELACSYM_IMAGE:-elacsym:latest}
    environment:
      ELACSYM_NODE_ID: indexer-2
      ELACSYM_NODE_ROLE: indexer
      AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER:-minioadmin}
      AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD:-minioadmin}
      ELACSYM_STORAGE_S3_BUCKET: ${ELACSYM_S3_BUCKET:-elacsym-data}
      ELACSYM_STORAGE_S3_REGION: ${ELACSYM_S3_REGION:-us-east-1}
      ELACSYM_STORAGE_S3_ENDPOINT: ${ELACSYM_S3_ENDPOINT:-http://minio:9000}
      ELACSYM_STORAGE_S3_WAL_PREFIX: ${ELACSYM_WAL_PREFIX:-production}
    volumes:
      - ./config-indexer.toml:/etc/elacsym/config.toml
      - indexer2_cache:/var/cache/elacsym
    ports:
      - "3002:3000"
    depends_on:
      - minio-init

  indexer-3:
    image: ${ELACSYM_IMAGE:-elacsym:latest}
    environment:
      ELACSYM_NODE_ID: indexer-3
      ELACSYM_NODE_ROLE: indexer
      AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER:-minioadmin}
      AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD:-minioadmin}
      ELACSYM_STORAGE_S3_BUCKET: ${ELACSYM_S3_BUCKET:-elacsym-data}
      ELACSYM_STORAGE_S3_REGION: ${ELACSYM_S3_REGION:-us-east-1}
      ELACSYM_STORAGE_S3_ENDPOINT: ${ELACSYM_S3_ENDPOINT:-http://minio:9000}
      ELACSYM_STORAGE_S3_WAL_PREFIX: ${ELACSYM_WAL_PREFIX:-production}
    volumes:
      - ./config-indexer.toml:/etc/elacsym/config.toml
      - indexer3_cache:/var/cache/elacsym
    ports:
      - "3003:3000"
    depends_on:
      - minio-init

  query-1:
    image: ${ELACSYM_IMAGE:-elacsym:latest}
    environment:
      ELACSYM_NODE_ID: query-1
      ELACSYM_NODE_ROLE: query
      AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER:-minioadmin}
      AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD:-minioadmin}
      ELACSYM_STORAGE_S3_BUCKET: ${ELACSYM_S3_BUCKET:-elacsym-data}
      ELACSYM_STORAGE_S3_REGION: ${ELACSYM_S3_REGION:-us-east-1}
      ELACSYM_STORAGE_S3_ENDPOINT: ${ELACSYM_S3_ENDPOINT:-http://minio:9000}
      ELACSYM_STORAGE_S3_WAL_PREFIX: ${ELACSYM_WAL_PREFIX:-production}
    volumes:
      - ./config-query.toml:/etc/elacsym/config.toml
      - query1_cache:/var/cache/elacsym
    ports:
      - "3000:3000"
    depends_on:
      - indexer-1
      - indexer-2
      - indexer-3

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - query-1

volumes:
  minio_data:
  indexer1_cache:
  indexer2_cache:
  indexer3_cache:
  query1_cache:
