name: CI

on:
  push:
    branches:
      - main
      - master
      - "release/**"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo build
        uses: Swatinem/rust-cache@v2

      - name: Format check
        run: cargo fmt --all -- --check

      - name: Cargo check
        run: cargo check --workspace --all-targets

      - name: Run tests
        run: cargo test --workspace
