[package]
name = "elax-metrics"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = "1"
metrics = "0.21"
metrics-exporter-prometheus = "0.13"
once_cell = "1"
